name: CI

on:
  push:
    branches:
      - citest
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "18.x"
          registry-url: "https://npm.pkg.github.com"
      - name: "Install dependencies"
        run: |
          yarn
      - run: yarn pub
        env:
            NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
