name: CI

on:
  push:
    branches:
      - citest
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # GitHub Packagesへの公開のために.npmrcファイルをセットアップ
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
          registry-url: "https://npm.pkg.github.com"
      - name: Install dependencies
          run: yarn
      - run: |
          yarn build
          yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
